var num1 = 10;
var num2 = 2;
var res = 0;
res = num1 + num2;
console.log("sum :" + res);
res = num1 - num2;
console.log("Subtraction :" + res);
res = num1 * num2;
console.log("Multiplication :" + res);
res = num1 / num2;
console.log("Division :" + res);
num1++;
console.log("Value of num1 after increment :" + num1);
num2--;
console.log("Value of num2 after decrement :" + num2);
