var myTuple = [10, "Hello"];
console.log(myTuple);
var myTuple2 = [];
myTuple2[0] = 1;
myTuple2[2] = 3;
console.log(myTuple2);
var myTuple3 = [10, "Hello", "World", "typescript"];
console.log(myTuple3.length);
myTuple3.push(13);
console.log(myTuple3);
console.log(myTuple3.length);
console.log(myTuple3.pop());
console.log(myTuple3.length);
myTuple2[1] = 121;
myTuple2[0] = 11;
console.log(myTuple2);
var a = [10, "hello"];
var b = a[0], c = a[1];
console.log(b);
console.log(c);
